CREATE TABLE SHOP(
  ID   BIGINT(20),
  name VARCHAR
);
CREATE TABLE T_ORDER_0(
  ID   BIGINT(20),
  NAME VARCHAR(255),
  PRIMARY KEY (ID)
)ENGINE=INNODB DEFAULT CHARSET=UTF8 COMMENT='订单表';
CREATE TABLE T_ORDER_1(
  ID   BIGINT(20),
  NAME VARCHAR(255),
  PRIMARY KEY (ID)
)ENGINE=INNODB DEFAULT CHARSET=UTF8 COMMENT='订单表';