CREATE DATABASE swak DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
CREATE TABLE T_GOODS (
  ID       VARCHAR(100) NOT NULL,
  NAME     VARCHAR(100) DEFAULT NULL,
  REMARKS  VARCHAR(100) DEFAULT NULL,
  PRIMARY KEY (ID)
) ENGINE=INNODB DEFAULT CHARSET=UTF8 COMMENT='商品';